#!/usr/bin/env bash
# GNU/Linux startup script generated by JavaPackager plugin

SCRIPTPATH=$(dirname "$(readlink -e "$0")")

JAVA="$SCRIPTPATH/jre/bin/java"

BINARY="$SCRIPTPATH/FTCLive INTO THE DEEP 2025-6.4.2-runnable.jar"


JVMDefaultOptions=""
JVMOptionsFile="$SCRIPTPATH/FTCLive INTO THE DEEP 2025.l4j.ini"
[ -f "${JVMOptionsFile}" ] && while read -r option; do JVMDefaultOptions+=" $option"; done <<< $(sed "/^#.*$/d" "${JVMOptionsFile}")

JVMClassPath="$BINARY"

cd "$SCRIPTPATH"

# Instructions:
# https://stackoverflow.com/questions/11481742/how-can-i-run-a-java-gui-application-on-a-headless-linux-that-does-not-support-g
#
xvfb-run -a -e "${SCRIPTPATH}/xvfb-run.log" "${JAVA}" ${JVMDefaultOptions} -jar "${JVMClassPath}" $@

# "${JAVA}" ${JVMDefaultOptions} -jar "${JVMClassPath}" $@
exit 0
